8-Sprinters/ListyWave-front

src/app/layout.tsx
Hydration Error in BoilerPlate
<br>
- 가장 상위 layout.tsx에 head, body 태그 추가
<br>
- 보일러 플레이트에 JS 코드도 없는데 Hydration Error (서버측과 클라이언트측의 정보에 차이가 있다)는 콘솔에러..
- 아무 파일도 없는데 어떻게 Hydration Error가 나는가 싶었다.
- useRouter을 이용하며 에러가 난다는 콘솔에러라서, 에러메시지만 봐서는 폴더 구조에 문제가 있는가 했지만
- 검색 결과 가장 root의 layout.tsx에 head와 body 태그가 포함되지 않았을때 이러한 하이드레이션 에러가 난다고 한다!
<br>
<br>
- 드디어 콘솔 깨끗합니다. 바로 작업시작 가능!^^
=> Fix: 보일러플레이트 Hydration 에러 해결

src/components/NoData/NoDataComponent.tsx, src/components/SimpleList/SimpleList.tsx, src/components/exploreComponents/ListsRecommendation.tsx, src/components/exploreComponents/TrendingLists.tsx, src/components/exploreComponents/UsersRecommendation.tsx, src/lib/types/listType.ts
<br>
- No이미지 관련 오류를 해결하였습니다.
-
-
<br>
- 죄송합니다.. ㅠ 코드리뷰 반영하고 수정하고 급하게 머지시켜버렸더니 오류가 발생했습니다..
<br>
<br>
<br>
<br>
=> Hotfix: 탐색 no이미지 관련 오류 해결

src/app/collection/[category]/_components/Top3Card.css.ts, src/app/collection/[category]/_components/Top3Card.tsx, src/app/collection/[category]/page.css.ts, src/app/collection/[category]/page.tsx, src/app/list/[listId]/_components/ListDetailInner/CollectButton.tsx, src/app/list/[listId]/_components/ListDetailInner/Footer.tsx, src/app/list/[listId]/_components/ListDetailInner/index.tsx, src/app/search/_components/SearchListResult.css.ts, src/app/search/_components/SearchListResult.tsx, src/app/search/_components/Top3Card.css.ts, src/app/search/_components/Top3Card.tsx
<br>
- ListDetail화면의 Footer와 CollectButton에서 사용되는 userId Params를 제거했습니다.
- onClick으로 router.push 하던 url 수정했습니다.
- 그 외 css를 조금 수정했습니다.
<br>
<br>
=> Fix : Url변경에 따라 params 제거

src/app/list/[listId]/edit/page.tsx, src/app/list/create/_components/list/MemberSelector.tsx, src/app/user/[userId]/(follow)/_components/Header.tsx, yarn.lock
- 리스트 생성, 수정, 팔로우 페이지 에서 useParam userId 를 사용하던 로직을 제외하였습니다.
<br>
@kanglocal 현지님쪽도 작업필요해보입니다! 
<br>
=> Chore: list/listId 경로 변경 작업

src/app/_api/user/updateProfile.ts, src/app/layout.css.ts, src/app/layout.tsx, src/app/list/[listId]/edit/page.tsx, src/app/list/create/_components/CreateList.tsx, src/app/list/create/_components/item/ItemLayout.tsx, src/app/list/create/_components/item/Items.css.ts, src/app/list/create/_components/item/Items.tsx, src/app/list/create/_components/list/SimpleInput.tsx, src/app/list/create/page.tsx, src/lib/constants/toastMessage.ts, src/lib/types/listType.ts, src/lib/utils/toasting.ts, yarn.lock
- 리스트 생성 추가 리팩토링 진행
<br>
<br>
- 히스토리 관리를 위해 하나의 리스트에서 같은 아이템 타이틀을 2번 이상 쓸 수 없도록 검증  로직을 추가했습니다.
<br>
- 이번에 커밋 열심히 해봐서, 커밋별로 보셔도 괜찮을 것 같아요!ㅎㅎ
- 감사합니다!
<br>
=> Refactor: 리스트 생성

src/app/layout.css.ts, src/app/layout.tsx, src/app/list/create/_components/CreateList.tsx, src/app/list/create/_components/item/ItemLayout.css.ts, src/app/list/create/_components/item/ItemLayout.tsx, src/app/list/create/_components/item/Items.tsx, src/app/list/create/_components/list/LabelInput.tsx, src/lib/utils/toasting.ts, src/styles/GlobalStyles.css.ts
- 리스트 생성에서 발생한 오류를 수정했습니다.
- 1) 라벨 입력시 에러가 발생하는 문제
- 2) 아이템 key 동일 사용으로 뜨는 콘솔에러
<br>
- 에러 제보 감사드립니다!
=> HOTFIX: 리스트 생성 오류 수정

src/components/exploreComponents/Header.tsx
<br>
- 헤더 버튼 알림 누르면 account 페이지로 가는 버그 수정
-
-
<br>
- 해결 방법
- 테스트 계획
<br>
close: #88 
<br>
<br>
<br>
=> Hotfix: 헤더 버그 수정

src/app/layout.tsx, src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx, src/app/notification/_components/NotificationList.css.ts, src/app/notification/_components/NotificationList.tsx, src/app/notification/_components/NotificationListSkeleton.tsx, src/app/notification/_components/ProfileImage.css.ts
- 알림페이지  폰트 사이즈와 프로필 이미지를 살짝 줄였습니다.
- 메타 태그, 댓글 스크롤 등 사소한 변화를 줬습니다.
<br>
- 개요 참고
<br>
##관련 이슈
close #94 
<br>
<br>
- 폰트 줄였는데 괜찮은가요?
<br>
=> Refactor: 알림페이지 디자인 수정

src/app/_api/list/getAllList.ts, src/app/auth/redirect/kakao/page.tsx, src/app/page.tsx, src/app/start-listy/_components/CreateNicknameStep.tsx, src/app/start-listy/page.tsx, src/app/user/[userId]/_components/Card.css.ts, src/app/user/[userId]/_components/Content.css.ts, src/app/user/[userId]/_components/Content.tsx, src/app/user/[userId]/_components/FollowButton.tsx, src/components/BottomNav/BottomNav.tsx, src/components/exploreComponents/FollowButton.tsx, src/components/floatingButton/PlusOptionFloatingButton.tsx, src/lib/axios/axiosInstance.ts
- QA반영 및 기능 관련 코드 수정을 했습니다.
<br>
- 피드 페이지 무한스크롤 관련 코드를 수정했습니다.
- 하단 네브바 콜렉션 버튼 클릭시 로그인 여부 검증 로직을 수정했습니다.
- 비회원이 접근 불가능한 페이지 접속 후, 탐색페이지로 리다이렉트 시, 한 번 로그인 모달을 띄운 후 탐색페이지로 재진입 하는 과정에서 발생하는 중복 로그인 모달 발생 현상을 수정했습니다.
- 비회원이 팔로우 요청, 취소 보냈을 때 에러처리를 수정했습니다. (마이피드, 탐색)
- 일부 디자인 수정
- 피드페이지 리스트 호버 시 스타일 추가
- nodata 보일 때 높이 수정
- 로그인 시 보여줄 로딩 이미지 추가(@Nahyun-Kang 님께서 만들어 주신 로티 사용)
- 프로필 수정 method 로직 변경에 따른 request 요청 시 코드를 개선했습니다.
- 로그인 모달 필요할 때 상황에 따라 토스트 메세지 제거 및 모달 추가 (이슈 참고)
<br>
- 해결 방법
- 테스트 계획
<br>
- 화이팅
<br>
=> Hotfix/fix feed - QA반영 및 기능 관련 코드 수정

src/app/list/[listId]/_components/ListDetailOuter/HeaderRight.tsx, src/app/list/[listId]/_components/ListDetailOuter/ListInformation.css.ts, src/app/list/[listId]/_components/ListDetailOuter/ListInformation.tsx
<br>
- 비공개 게시물일 경우 히스토리 버튼이 노출 되지 않게 수정했습니다!
<br>
- 해결 방법
- 테스트 계획
<br>
close: #133 
<br>
<br>
<br>
=> Hotfix: 비공개 게시물 히스토리 버튼 노출 안 되게 수정

src/app/intro/_components/SearchBar.css.ts, src/app/intro/_components/Section6.tsx, src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
<br>
- 댓글 띄어쓰기만 되어도 작성되는 문제를 해결했습니다. (화면 상에 공란으로 뜨는 문제)
- 인트로 페이지의 UI를 일부 개선했습니다.(애니메이션 등장 딜레이, 검색창 크기 확대)
-
<br>
- 해결 방법
- 테스트 계획
<br>
<br>
<br>
<br>
=> Fix: 댓글 띄어쓰기만 되어도 작성되는 문제 해결, 인트로 페이지 UI 개선

src/app/list/[listId]/edit/page.tsx, src/app/list/create/_components/CreateList.tsx, src/app/list/create/_components/list/ButtonSelector.tsx, src/app/list/create/_components/list/LabelInput.tsx, src/app/list/create/_components/list/MemberSelector.tsx, src/app/list/create/_components/list/RadioInput.tsx, src/app/list/create/_components/list/SimpleInput.css.ts, src/app/user/[userId]/(follow)/_components/Header.tsx, src/components/Header/Header.css.ts, src/components/Header/Header.tsx, src/lib/types/listType.ts
<br>
-
-
-
<br>
- 해결 방법
- 테스트 계획
<br>
<br>
<br>
<br>
=> QA 반영 완료 (Assignee 안유진)

src/app/not-found.css.ts, src/app/not-found.tsx
- 404 페이지 탈출 버튼을 만들었습니다.
<br>
<br>
<br>
=> Feat: 404 페이지 탈출 버튼

src/components/UserProfileImage/UserProfileImage.tsx
- 이미지 로드 실패 처리 방식 변경 (fetch로 시도 -> next/Image onError 이용)
=> 프로필이미지 컴포넌트 이미지 로드 실패시 next/Image onError 이용

src/app/account/locale.ts, src/app/collection/[category]/_components/NoData.tsx, src/app/collection/[category]/_components/Top3Card.css.ts, src/app/collection/[category]/_components/Top3Card.tsx, src/app/collection/[category]/page.tsx, src/app/collection/locale.ts, src/app/collection/page.tsx, src/app/list/[listId]/_components/ListDetailInner/RankList.tsx, src/app/search/Search.css.ts, src/app/search/_components/CategoryArea.css.ts, src/app/search/_components/CategoryArea.tsx, src/app/search/_components/NoData.tsx, src/app/search/_components/SearchListResult.tsx, src/app/search/_components/SearchResult.css.ts, src/app/search/_components/SearchUserResult.tsx, src/app/search/_components/Top3Card.css.ts, src/app/search/_components/Top3Card.tsx, src/app/search/locale.ts, src/app/search/page.tsx, src/app/search/util/makeSearchUrl.ts, src/components/SelectComponent/SelectComponent.tsx
<br>
- 멘토님 QA시 나온 이슈 일부 수정했습니다.
- search, collection쪽 Locale 수정했습니다.
=> Fix : locale 및 UI 수정

src/app/list/create/_components/item/ItemLayout.tsx, src/app/list/create/_components/item/Items.css.ts, src/app/list/create/_components/item/Items.tsx, src/app/list/create/_components/item/LinkModal.css.ts, src/app/list/create/_components/item/LinkModal.tsx, src/app/user/[userId]/(follow)/_components/Header.tsx, src/components/UserProfileImage/UserProfileImage.css.ts, src/components/UserProfileImage/UserProfileImage.tsx, src/lib/constants/placeholder.ts
- 이슈를 해결했습니다.
<br>
- 리스트 생성 아이템 링크 http:// 추가 로직 수정
- 리스트 생성  링크 미리보기 도메인만 나오도록 수정
- 아코디언 박스가 아닌 열림/닫힘 아이콘 클릭으로 상태 관리
- 팔로잉/팔로워  목록 헤더 공용  컴포넌트로 수정
- 공용 프로필 이미지 비율 고정으로 사진 찌부되는 현상 수정
<br>
close: #113 
<br>
-늦어서 죄송합니다ㅠㅠ
<br>
=> Fix: 리스트생성의 아이템 링크, 아코디언 & 팔로잉 목록 헤더 & 공용 프로필이미지 컴포넌트 오류 수정

src/app/list/create/_components/item/Items.tsx, src/app/list/create/_components/item/LinkPreview.tsx
- 링크 미리보기 연결 url 오류 해결
<br>
- 오류를 수정합니다.
=> HOTFIX: 링크 미리보기 연결 url 오류 해결

src/app/collection/page.css.ts
- 제목 참고
<br>
- margin대신 Padding 사용
<br>
- 콜렉션 부분 윗 색깔 안채워지는 오류가 있었습니다! 캡쳐에 참고 부탁드립니다!
<br>
=> Design: 상단 색 채워지지 않는 오류 해결

src/app/list/[listId]/_components/ListDetailOuter/CommentForm.tsx, src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
<br>
- 댓글 엔터 버튼 두 번 누르면 그대로 댓글이 두 개 생성되는 문제를 발견하여 submit button disabled 처리 했습니다. 
<br>
<br>
<br>
<br>
- 놓치고 있었다가 얼른 처리했습니다..! 🥹
<br>
=> Hotfix: 댓글,답글 생성/수정 요청중 submit 버튼 disabled 처리

public/icons/chevron_right_double.svg, src/app/search/_components/CategoryArea.css.ts, src/app/search/_components/CategoryArea.tsx
<br>
- 기존 메세지가 뜨던 UI를 화살표로 수정했습니다.
<br>
=> Fix : 검색 > 스크롤 안내 UI수정

src/components/exploreComponents/UsersRecommendation.tsx
<br>
-탐색 페이지 사용자 추천 리스트 비회원일 경우 계속 떠있는 이슈를 해결
-
-
<br>
- 해결 방법
- 테스트 계획
<br>
close: #172
<br>
<br>
<br>
=> Hotfix: 탐색 페이지 사용자 추천 리스트 비회원일 경우 계속 떠있는 문제 해결

src/app/collection/locale.ts, src/app/collection/page.tsx
<br>
- collection locale 수정했습니다.
=> Fix : collection locale 수정

src/app/intro/_components/Section5.tsx, src/app/intro/_components/Section6.tsx
<br>
- 급하게 인트로 페이지 alt 문구 삭제하였습니다!
-
-
<br>
- 해결 방법
- 테스트 계획
<br>
<br>
<br>
<br>
=> Hotfix: 인트로 페이지 alt 문구 삭제

src/app/layout.tsx, src/app/search/_components/SearchListResult.tsx
<br>
- useEffect의 dependencyList를 수정해보았습니다. 
- 배포에서만 발생하는 에러여서 머지해보겠습니다.
=> fix: 버그 수정 시도합니다

src/app/search/_components/SearchListResult.tsx
=> Fix: useEffect삭제해봄

src/app/list/[listId]/edit/page.tsx
- 리스트 수정 API 요청시 콜라보레이터 ID 목록에 본인ID 제외
<br>
=> Hotfix: 리스트 수정 API 요청시 콜라보레이터 ID 목록에 본인ID 제외

src/app/account/profile/_components/ImagePreview.tsx, src/app/account/profile/_components/ProfileForm.css.ts, src/app/account/profile/_components/ProfileForm.tsx, src/app/account/profile/_components/ProfileSkeleton.tsx, src/app/account/profile/page.tsx, src/components/Skeleton/Skeleton.css.ts, src/components/Skeleton/Skeleton.tsx
- 무거운 mui 제거를 위한 단계1. 스켈레톤 직접 구현
<br>
- 스켈레톤 공용 컨포넌트 제작
- 프로필 설정 스켈레톤 교체 (mui -> 공용 컴포넌트)
<br>
- 다른 스켈레톤들도 점차 바꾸겠습니다.
- 아코디언UI도 MUI를 사용 중이라, 추후 아코디언UI도 교체해야 할 것 같습니다!
<br>
#201 
<br>
- opacity가 진해졌다 연해졌다 반복하는 애니메이션으로 사용했습니다.
- 속성으로는 width(number), height(number), borderRadius(string)를 받고, 모두 Optional 합니다.
-  default 값은 width: 100%, height: 100%, borderRadius: 4px
- 확인 부탁드립니다! 🍀
=> Refactor: 프로필 설정 스켈레톤 직접구현 컴포넌트로 교체

next.config.js, src/app/list/create/_components/list/LabelInput.tsx, src/app/page.tsx, src/lib/constants/placeholder.ts
- 안드로이드 폰 특정 키배열에서 엔터로 라벨 생성이 되지 않는 이슈
- 스페이스바로 라벨 입력 가능하도록 수정
<br> "
=> Fix: 스페이스바 입력으로 라벨 생성 가능하도록 기능 추가

src/app/collection/[category]/_components/Top3Card.tsx, src/app/list/[listId]/_components/ListDetailInner/index.tsx, src/app/list/[listId]/edit/page.tsx, src/app/list/create/_components/CreateList.tsx, src/app/list/create/_components/list/ColorSelector.tsx, src/app/list/create/_components/list/PaletteSelector.css.ts, src/app/list/create/_components/list/PaletteSelector.tsx, src/app/list/create/locale.ts, src/app/list/create/page.tsx, src/app/search/_components/Top3Card.tsx, src/app/user/[userId]/_components/Card.tsx, src/components/exploreComponents/TrendingLists.tsx, src/lib/types/listType.ts, src/styles/Color.ts
- 리스트 배경색 확장 및 팔레트 도입
- 리스트 배경을 hex 원시값을 이용해 API 통신하는 방식에서 컬러코드로 API 통신하는 방향으로 수정 (은닉, 보호 목적)
<br>
=> ListyWave ver2.4.0 : 리스트 배경색 확장 및 팔레트 도입

src/app/auth/redirect/kakao/page.tsx, src/app/collection/page.css.ts, src/app/collection/page.tsx, src/app/intro/_components/Footer.tsx, src/app/intro/_components/Section3.tsx, src/app/intro/locale.ts, src/app/list/[listId]/_components/ListDetailOuter/Comment.css.ts, src/app/list/[listId]/_components/ListDetailOuter/Comment.tsx, src/app/list/[listId]/_components/ListDetailOuter/CommentForm.tsx, src/app/list/[listId]/_components/ListDetailOuter/Replies.css.ts, src/app/list/[listId]/_components/ListDetailOuter/Replies.tsx, src/components/login/LoginModal.tsx, src/lib/axios/axiosInstance.ts, src/lib/utils/cookie.ts, src/store/useUser.ts
- 댓글기능추가
- 리프레시토큰 만료기간 재설정
- 개인정보처리방침페이지
- 콜렉션페이지 바텀 네비게이션에 가려지는 하단부 여백 추가
=> ListyWave ver2.4.2 : 댓글기능추가/리프레시토큰 만료기간 재설정/개인정보처리방침페이지/콜렉션페이지 UI수정
