8-Sprinters/ListyWave-front

.github/workflows/CI.yml
.github/workflows/Dev-CD.yml

- `dev` 브랜치에 해당하는, 프론트엔드 개발 서버의 CI/CD 구축 완료 했습니다!
- 프론트엔드 CI/CD는 처음이라 많이 헤매다가 너무 지체되는 거 같아 일단 동작은 하게끔 했어요..!
보안을 강화하거나 성능 개선 할 여지가 있지만 둘 다 차차 진행하도록 하겠습니다!
- 적용법이나 가이드 문서는 나중에 보안적으로나 성능적으로 완성되면 작성하고자 합니다.
<br>
- AWS CloudFront, S3 이용해 배포
- Github Actions 이용해 CI/CD 구축
<br>
- 파일이 많아짐에 따라 build 시간이 길어져서 배포하는 데까지 시간이 오래 걸릴 수 있어요.
이건 불편함을 느끼실 때 다시 작업하는 걸로 하겠습니다!
<br>
<br>
<br>
<br>

infra: 프론트엔드 개발 서버 CI/CD 구축

---

.github/workflows/Dev-CD.yml

- CD workflow 상에서 S3로 올리는 과정 중, `delete-removed` 옵션을 `true`로 추가했습니다.
- `delete-removed`: Removes files in S3, that are not available in the local copy of the directory
- S3에 올라가있지만, Github Repository(local)에서는 제거된 파일을 S3에서도 제거하는 옵션.. 으로 이해했습니다!
- 그래서 켰습니다.
<br class="Apple-interchange-newline">
<br>
- CD workflow에 `delete-removed` 옵션을 `true`로 추가
<br>
- 서영님이 알려주셨습니다!
[참고 링크](https://github.com/8-Sprinters/ListyWave-front/pull/6#discussion_r1468359462)
<br>
- #6 
<br>
<br>
<br>

infra: delete-removed 옵션 true로 추가

---

public/icons/dnd.svg
src/app/create/_components/CreateItem.tsx
src/app/create/_components/item/ItemLayout.css.ts
src/app/create/_components/item/ItemLayout.tsx
src/app/create/_components/item/Items.css.ts
src/app/create/_components/item/Items.tsx
src/app/create/page.tsx
src/app/user/[userId]/list/[listId]/page.tsx
src/lib/types/listType.ts
src/lib/utils/toasting.ts
yarn.lock

- 리스트생성 리퀘스트에 imageUrl 필드를 빼고 보내, 리스트 조회시 null값으로 인한 에러가 발생하는 현상을 해결했습니다.
- 해결방법: imageUrl 필드에 빈문자열 넣기
- 아이템 타이틀 필드 양옆 아이콘이 배포 환경에서 가려지는 에러가 있어 수정했습니다. 로컬과 yarn build-start 환경에서 확인이 불가능하여 함께 올립니다.
<br>
<br>
- 리스트 생성 후 상세 페이지로 리다이렉트 할 때, listId를 이용해 이동해야해서 useState를 사용했습니다. (@ParkSohyunee 도움 주셔서 감사합니다🙇‍♀️)
- 리다이렉트 링크는 수정된 url인 user/[userId]/list/[listId] 입니다!
- 아직 토스트메시지 상수화 이전입니다! 참고 부탁드립니다~!
- 앱라우팅에서 UseRouter의 경로는 `import { useRouter } from 'next/navigation'` 라는 것을 배웠습니다.
<br>
- 확인 부탁드려요 :)

HOTFIX: 리스트생성 imageUrl 미삽입으로 인한 에러 해결 및 기타 수정

---

src/app/_api/list/getAllList.ts
src/app/user/[userId]/_components/Card.css.ts
src/app/user/[userId]/_components/Card.tsx
src/app/user/[userId]/_components/Categories.css.ts
src/app/user/[userId]/_components/Categories.tsx
src/app/user/[userId]/_components/Content.css.ts
src/app/user/[userId]/_components/Content.tsx
src/app/user/[userId]/_components/FollowButton.css.ts
src/app/user/[userId]/_components/Profile.css.ts
src/hooks/useIntersectionObserver.ts

- 마이리스트, 콜라보리스트 페이지 전체 리스트 무한스크롤을 구현했습니다.
<br>
- react-query를 사용한 리스트 목록조회 무한스크롤 기능
- scroll 감지 observer api 커스텀 훅 생성 (useIntersectionObserver)
- 페이지 관련 컴포넌트 스타일 색상 공용 컬러 변수로 변경
- 기타 일부 스타일 수정
<br>
- 리스트 페이지 추가 작업 예정 목록입니다. 참고 부탁드립니다.
<br>
<br>
- 현재 한번에 불러오는 리스트 개수(size)를 5개로 설정해 놓았는데, QA 테스트 후 size 변경 가능성도 있습니다.
- observer api 커스텀 훅 사용하시다가 수정이 필요한 부분 있으시면 말씀 부탁드립니다.
<br>

Feat: 마이리스트, 콜라보리스트 페이지 전체 리스트 조회 무한스크롤 구현

---

src/lib/axios/axiosInstance.ts

- 백엔드 Authorization 헤더 prefix 수정에 따른 axiosInstance config에 Bearer 옵션 추가
<br>
-  axiosInstance config에 Bearer 옵션 추가
<br>
-  api를 잘 불러오고 있습니다!!!
<br>
- 해당 pr merge전까지는 로그인을 해도 Unauthorize 에러가 발생하고 있습니다. 참고 부탁드립니다.
<br>

HOTFIX: axiosInstance config에 Bearer 옵션 설정

---

src/app/[userNickname]/[listId]/_components/ListDetailInner/Footer.tsx
src/app/_api/follow/createFollowUser.ts
src/app/_api/follow/deleteFollowUser.ts
src/app/_api/list/getAllList.ts
src/app/_api/user/getUserOne.ts
src/app/layout.tsx
src/app/user/[userId]/_components/Card.tsx
src/app/user/[userId]/_components/Content.tsx
src/app/user/[userId]/_components/FollowButton.css.ts
src/app/user/[userId]/_components/FollowButton.tsx
src/app/user/[userId]/_components/Profile.tsx
src/lib/constants/queryKeys.ts
src/lib/constants/toastMessage.ts
src/lib/types/listType.ts
src/lib/utils/numberFormatter.ts

- 마이리스트, 콜라보리스트 페이지에서 팔로우/팔로잉 기능을 구현했습니다.
<br>
- 사용자 프로필에서 [팔로우] 버튼을 클릭하면 해당 사용자를 팔로잉하게 됩니다.
- 이미 팔로잉한 사용자라면 [팔로우 취소] 버튼이 보이고, 버튼을 클릭하면 해당 사용자 팔로우를 취소하게 됩니다.
- 로그인한 상태가 아니라면 [팔로우] 버튼만 보이고, 버튼을 클릭하면 로그인 페이지로 이동하게 됩니다. (+. 토스트 메세지)
- 위의 3가지 상태에 따른 프로필 상태 UI 반영 
- 팔로잉 여부에 따른 본인 프로필, 팔로우 한 사용자 프로필 count update
- 팔로우 요청 제한 설정(최대 1천명) (*팔로워는 제한 x) (+. 토스트 메세지)
- 본인 리스트 접근 시에는 [팔로우] 버튼 대신 설정(마이페이지 이동) 아이콘이 보임
- 리스트 목록 중 아이템 리스폰스 타입 수정 (ranking -> rank)
<br>
- 리스트 조회 페이지에서 사용자 프로필 조회시, 팔로우된 상태 여부를 리스폰스로 받아옵니다.
ㄴ 현재 팔로우 요청이 정상적으로 들어간 이후에도 사용자에게 반영되지 않은 상태라서, 백엔드의 수정이 필요한 부분입니다. (완료)
ㄴ 내일까지 수정 요청 드릴 예정이며, 이후 스크린샷 첨부하도록 하겠습니다. 
<br>
- 내일 api 수정 후 반영하여 스크린샷 첨부하도록 하겠습니다. 📸 (첨부 완료)
<br>
- **위의 참고사항 내용 확인 및 반영 후에 최종 merge 예정입니다.** (완료)
- 코드 자체는 큰 수정이 없을 것 같아서 PR 먼저 올립니다. 리뷰는 시간나실 때 천천히 부탁드립니다. 감사합니다. …

Feat: 마이리스트, 콜라보리스트 페이지 팔로우 기능 구현

---

src/app/_api/follow/deleteFollower.ts
src/app/_api/follow/getFollowerList.ts
src/app/_api/follow/getFollowingList.ts
src/app/_api/user/getUsersByNicknameSearch.ts
src/app/list/create/_components/CreateList.tsx
src/app/list/create/_components/list/MemberSelector.tsx
src/app/user/[userId]/(follow)/_components/UserList.css.ts
src/app/user/[userId]/(follow)/_components/UserList.tsx
src/app/user/[userId]/(follow)/followers/page.tsx
src/app/user/[userId]/(follow)/followings/page.tsx
src/app/user/[userId]/list/[listId]/edit/page.tsx
src/lib/constants/queryKeys.ts
src/lib/types/followType.ts
src/lib/types/user.ts

- 리스트 생성 및 수정페이지에서 팔로잉 유저 조회 API  및 유저 검색 API 연결
- 팔로잉 조회, 팔로워 조회 페이지 API 연결 및 구현
<br>
[ 팔로잉 팔로워 조회 페이지 ]
- 팔로잉 팔로워 페이지 API 연결
- 팔로잉 페이지 취소 버튼 없앰
- 본인의 팔로워 조회 페이지일때만 팔로워 삭제버튼이 보이도록 함.
[ 리스트 생성 수정 페이지 ]
- 콜라보레이터 수정에서 유저 검색 API 느림 이슈 해결
- 콜라보레이터 추가 박스 클릭시 팔로잉 리스트 조회, 검색
- 생성, 수정페이지 둘 다에서 선택한 유저가 아래에 잘 추가되고 삭제도 잘 동작합니다.
<br>
- 디바운스와 무한스크롤은 백로그로.. 아직 팔로워가 10명 미만으로 많지 않아서 히스토리 먼저 하고 이 브랜치 다시 돌아오겠습니다.
- 팔로워 삭제 기능은 내일 중으로 API 주신다고 하네요!! API 받고 삭제하시겠습니까 모달과 함께 연결하겠습니다
<br>
- 콜라보레이터 수정에서 유저 검색 API 느림 이슈 해결
- 아래처럼 id를 포함해서 쿼리키를 지정해줬어야했는데, 리액트 쿼리에서 계층적 쿼리키 지정을 해주지 않아서 생긴 문제였습니다.
- 마운트 된 후 useUser가 정보를 가져오기 전에 유저 0번으로 리액트 쿼리가 실행되어 캐싱된 값이 계속 유지가 되었고, 이로인해 이 캐싱이 gc에 의해 클리어 되기 전까지 이 값이 유지가 되어서 실제 id에 대한 쿼리실행결과를 가져오는데 오래 걸린거였답니다..! 
<br>
1. 콜라보레이터 추가 박스 처음 클릭했을때
2. 콜라보레이터 추가 박스에 검색했을때
3. 팔로잉 조회 페이지
4. …

Feat: 팔로잉/팔로워 조회 페이지 API 연결 및 리스트 생성 페이지 유저 검색 API 연결 완료

---

package.json
src/app/account/_components/LogoutModal.tsx
src/app/auth/redirect/kakao/page.tsx
src/app/layout.tsx
src/app/page.tsx
src/app/user/[userId]/_components/FollowButton.tsx
src/components/BottomNav/BottomNav.tsx
src/lib/axios/axiosInstance.ts
src/lib/constants/toastMessage.ts
src/lib/types/user.ts
src/lib/utils/cookie.ts
src/middleware.ts
yarn.lock

- refreshToken(RT)로 만료된 accessToken(AT)를 재발급 받는 기능을 구현했습니다.
<br>
- 기존 로컬스토리지에 저장한 AT를 리액트 쿠키를 사용하여 쿠키에 저장하는 것으로 변경하였습니다.
- 미들웨어를 추가하여 페이지 접근 권한 처리를 하였습니다.
- axios interceptors로 api 요청 시 토큰 만료된 경우에 대한 에러 핸들링을 하였습니다.
- 탈퇴한 회원에 대해 로그인 시 탈퇴페이지로 리다이렉트 처리를 추가하였습니다.
- 공통 바텀 네비게이션 컴포넌트에서 마이피드 접근 시, 비회원인 경우 토스트 메세지를 추가하였습니다.
- 쿠키 만료시간을 AT는 30분, RT는 24시간으로 설정하였습니다.
- [  ] 이 부분은 추후 처음에 RT를 받을 때 쿠키로 받는 로직으로 변경 될 예정이기 때문에, 그 전까지 관리를 위해 설정하였습니다.
- 즉, 24시간마다는 로그인이 필요합니다.
<br>
- 추후 작성하여 첨부하겠습니다.
<br>
- 추후 작성하여 첨부하겠습니다.
<br>
- 추후 작성하여 첨부하겠습니다.
<br>
- 늦게 올려서 죄송합니다!! 테스트 하면서 추가로 에러 핸들링 할 부분이 발생할 것 같아서 계속 보완해나가겠습니다. 감사합니다.
<br>

Feat: 로그인 refreshToken 도입 및 인가 처리

---

src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
src/app/notification/_components/NotificationList.tsx

- 알림 클릭 경로 수정
<br>
- 알림 클릭시 이동하는 경로를 수정했습니다. 'user/userId/list/listId' -> 'list/listId'
- 댓글/답글 클릭시에는 댓글 컴포넌트 쪽으로 스크롤이 내려갑니다.
<br>
- 댓글 알림 이동 (자동 스크롤)
<br>
- 알림 확인 부탁드려요 ㅎㅎ
<br>

Fix: 리스트상세 URL 변경에 따른  알림 클릭시 이동 경로 변경

---

src/app/layout.tsx
src/app/list/[listId]/edit/page.tsx
src/app/list/create/page.tsx

- 리스트 생성, 수정 완료 후 상세페이지 이동시, 리스트 생성/수정의 히스토리가 남지 않는다
<br>
- router.push 대신 router.replace로 이동
- layout 일부 코드를 살짝 수정했습니다.
- 파이팅!
<br>

Refactor: 리스트  수정, 생성   페이지는 히스토리 기록에 남지 않도록 수정

---

src/app/layout.tsx
src/app/list/create/_components/item/ItemLayout.tsx
src/styles/GlobalStyles.css.ts

- 여러 UX 불편 사항 개선 작업 진행
<br>
- 리스트 생성 아이템의 아코디언 UI 열림 상태를 default로 수정
- 메타 태그 설정 방법을 다르게 했습니다.
- 버튼 뒷배경 없애는 코드에 important를 줬습니다.

Refactor: 아코디언 default 열림 상태, 메타 태그 재설정, 버튼 뒷 배경 없애기 재시도

---

src/app/user/[userId]/_components/Profile.tsx

- 마이피드 url 접근 시, 사용자 케이스에 따른 에러처리를 추가했습니다.
<br>
- 탈퇴한 회원이거나(400), 잘못된 id거나(400), 없는 회원(404)인 경우 에러처리
- 모달 연동 및 확인 버튼 누르면 탐색페이지로 리다이렉트
- 모달 내 커스텀 에러메세지
<br>
- 해결 방법
- 테스트 계획
<br>
<br>
- 화이팅
<br>

Feat: 마이피드 접근 시, 에러 케이스(탈퇴 / 잘못된id 입력 / 없는 사용자)에 따른 에러처리 로직 추가

---

src/app/list/[listId]/history/page.css.ts
src/app/list/[listId]/history/page.tsx

- 히스토리 페이지에서 사용한 공용헤더만 position: sticky가 적용되지 않아 상단 고정 되고 있지 않던 이슈를 해결했습니다.
<br>
- position: sticky 는 body 태그 처럼 height가 지정된 부모를 가져야하고 부모태그에 overflow 속성이 없어야만 적용됩니다.
<br>

Fix: 히스토리 페이지 헤더 상단 고정 안 됨 이슈 해결

---

src/app/_api/list/getAllList.ts
src/app/user/[userId]/_components/Content.tsx
src/lib/types/listType.ts

- 리스트 전체 조회 api 필드 값 변경으로 인한 타입, 쿼리 프로퍼티 수정
<br>
- 리스트 전체 조회 cursorId 값이 기존 리스트 고유 id 값에서 리스트 업데이트 값으로 변경
ㄴ 그 이유는, 트랜딩, 검색페이지 등 리스트를 최신순으로 유지해야 하는데 id값으로 정렬하면 리스트 수정 등이 발생했을 때 리스트 목록이 중간중간 비는 현상 발생
ㄴ 리스트 전체 관리를 위해 리스트 관련 고유값을 cursorUpdatedDate으로 변경
- api 파라미터, 리스폰스 타입, 리액트 쿼리 파라미터를 수정
<br>
<br>
<br>
<br>
<br>

Fix: 리스트 전체 조회 api 필드 값 변경으로 인한 타입, 쿼리 프로퍼티 수정

---

src/app/list/[listId]/history/_component/HistoryGraph.tsx
src/app/list/[listId]/history/_component/HistoryVersions.tsx
src/app/list/[listId]/history/page.css.ts
src/app/list/[listId]/history/page.tsx

- 히스토리 페이지에서 순위가 1.0위 처럼 float로 표시되었는데 순위를 int로 변경했습니다.
- 히스토리 버전 페이지에서 순위 기준 정렬로 보여지게 했습니다.

히스토리 페이지 - 순위 float로 표시되던 순위를 int로 변경 및 순위 기준 정렬

---

src/app/list/[listId]/edit/page.tsx
src/lib/types/listType.ts

- 리스트 수정시 콜라보레이터가 1명 이상일때 owner ID 포함시켜 API 호출, 콜라보레이터가 0명일때는 빈배열로 API 호출로 변경

Fix: 리스트 수정 - 콜라보레이터가 1명 이상일때 owner ID 포함시켜 API 호출로 변경

---

src/app/list/[listId]/_components/ListDetailInner/Header.tsx
src/app/list/[listId]/_components/ListDetailInner/RankList.css.ts
src/app/list/[listId]/_components/ListDetailInner/RankList.tsx
src/app/list/[listId]/_components/ListDetailInner/index.tsx

<br>
- 리스트 상세 이미지를 img태그로 변경했습니다.
( next/Image 태그를 사용할경우 높이지정이 되지않는 문제가 있었습니다. 추후 수정하겠습니다.)
- 리스트상세페이지의 초기값을 detail로 변경했습니다.

Fix : 리스트상세 이미지 및 리스트의 타입 초기값을 detail로 변경

---

public/icons/folder_food.svg
src/app/account/_components/LanguageDropdown.tsx
src/app/account/page.tsx
src/app/account/profile/page.tsx
src/app/account/withdraw/_component/WithdrawalHeader.tsx
src/app/collection/page.tsx

- 자잘한 오류를 해결했습니다.
<br>
- 콜렉션  페이지에  추가된 '음식' 카테고리의 폴더 이미지를  추가했습니다.
- 마이페이지에 언어선택 '한국어' 표시를 수정했습니다.
- 마이페이지 '의견 보내기' 버튼에 설문 링크를  추가했습니다.
- 탈퇴하기 페이지 헤더 뒤로가기 버튼에 '링크 이동'이 아닌 '뒤로가기' 동작을 추가했습니다.
- 프로필 설정시 input에 에러가 있어도 버튼이 활성화 되는 것을 막았습니다.
<br>
- '의견보내기'에 우선 tally로 간단하게 설문 만들어 연결해두었습니다! 추후 공용 지메일로 설문 제대로 만들어보아요~!

Fix: 콜렉션, 마이페이지, 탈퇴하기, 프로필 설정 오류 해결

---

src/app/account/profile/page.tsx

- 프로필 이미지가 바뀌어도 저장 버튼이 활성화 되지 않는 이슈를 해결합니다.
<br>
- 비활성화 조건 수정

HOTFIX: 프로필 설정 '저장'버튼 비활성화 오류 해결

---

src/app/layout.tsx

- 핸드폰에 바로가기를 추가했을때 앱처럼 아이콘이 보여지도록 head 태그에 link 추가
<br>
<br>
<br>
변경 전
변경 후
<br>

모바일앱 아이콘 추가

---

src/app/search/page.tsx

- 배포 버전에서 발생하는 검색페이지 진입 시 무한렌더링 이슈 해결 시도
<br>
- /search/page.tsx 에서 useEffect문 주석 처리
<br>
- 정확히 어느 부분이 문제인지 개발 버전에서 확인이 어려워 우선 페이지 useEffect문을 주석처리 해 보았습니다.
<br>
- 현지님, 우선 오류를 빨리 해결해야 할 것 같아서 1차 시도를 해보았습니다. 참고 부탁드립니다.🥲
- 만약 해당 pr 머지 후 무한렌더링이 해결된다면, 그 이후 관련기능에 대해서는 현지님께서 확인 부탁드립니다!!
<br>

Fix: 검색페이지 배포 시, 무한렌더링 이슈 해결을 위한 useEffect문 주석 처리 시도

---

src/app/intro/_components/Footer.tsx
src/app/layout.tsx
src/app/list/[listId]/_components/ListDetailInner/CollectButton.tsx
src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
src/app/login/page.tsx
src/app/page.tsx
src/app/user/[userId]/_components/FollowButton.tsx
src/components/BottomNav/BottomNav.tsx
src/components/exploreComponents/FollowButton.tsx
src/components/exploreComponents/Header.tsx
src/components/floatingButton/PlusOptionFloatingButton.tsx
src/components/login/LoginModal.tsx
src/lib/utils/gtag.tsx
src/lib/utils/gtm.tsx

- GTM(Google Tag Manager) 이용을 위한 코드를 삽입했습니다.
- 로그인 버튼 클릭 특정을 위해, 로그인버튼 Link 태그에 id를 삽입했습니다.
<br>
- `/intro`: `introLoginBtn`
- `/`: `headerLoginBtn`, `redirectedLoginBtn`(접근불가 페이지 접속시 리다이렉트 된 경우), `exploreFollowLoginBtn`
- `/` or `/user` : `floatingLoginBtn`
- `/search` or `/`:  `bottomNavLoginBtn`
- `/user` : `followLoginBtn`
- `/list`: `collectLoginBtn`, `commentLoginBtn`, `DuplicateList`
- `/login`: `loginPageBtn`
<br>
- 참고  링크: https://datarian.io/blog/create-gtm-account

feat: 구글태그매니저(gtm) 스니펫 삽입

---

src/app/list/[listId]/_components/ListDetailOuter/Comment.css.ts
src/app/list/[listId]/_components/ListDetailOuter/Comment.tsx
src/app/list/[listId]/_components/ListDetailOuter/CommentForm.tsx
src/app/list/[listId]/_components/ListDetailOuter/Comments.css.ts
src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
src/app/list/[listId]/_components/ListDetailOuter/Replies.tsx
src/hooks/useEnterKeyDown.ts
src/store/useComment.ts

<br>
- 댓글 폼을 TextArea로 바꾸었습니다. (바꾸고 나니 엔터키를 누르면 바로 전송이 안됐지만 엔터키를 누르면 폼이 전송되도록 하는 키보드 함수를 추가했습니다.)
- 댓글 수정과 답글 생성이 동시에 가능하지 않도록 수정했습니다.
- 답글 수정 이후 재렌더링이 일어나지 않는 이유를 발견했습니다. (쿼리 무효화 함수 수정)
<br>
- useResizeTextarea 훅을 사용했습니다. 
- 훅을 사용하여 폼 전송하고 이후 자동으로 크기가 줄어들게 하고 싶었는데, blur/focus 이외에는 폼의 크기를 되돌릴 수 있는 방법을 찾지 못했습니당..(일단 임시로 하드코딩 해두었습니다)
<br>
closed: #196 
closed: #208
closed: #209 
<br>
댓글 textarea로 수정, 댓글수정/ 답글 달기 동시에 되는 문제 해결
https://github.com/8-Sprinters/ListyWave-front/assets/142777396/69a5d6f0-e1a2-4ff0-8012-09b808b46018
답글 수정 반영 안되는 버그 해결
https://github.com/8-Sprinters/ListyWave-front/assets/142777396/7a20e82b-679a-4cfa-8166-40b2ff286e15
<br>
<br>

Fix: 댓글 폼 TextArea로 수정, 댓글/답글 관련 버그 수정

---

src/app/list/[listId]/_components/ListDetailInner/Footer.tsx
src/app/list/[listId]/_components/ListDetailInner/getBottomSheetOptionList.ts
src/app/list/[listId]/locale.ts

- 리스트 상세 '이 타이틀로 리스트 생성하기'를 비회원이 접속 할 경우의 로직을  수정했습니다.
**현재:** 클릭 -> 생성페이지 -> userId가 없어 '/'으로 redirect 및 login 모달 열림 (=>탐색 페이지)
**변경:** 클릭 -> userId가 없으면 로그인 모달 열림 (=>여전히 해당 리스트상세 페이지)
<br>
- 비회원 '이 타이틀로 리스트 생성하기' 버튼 클릭시 로그인 모달 띄우기
- 해당 로그인 모달의 버튼id추가 (생성페이지 이동 차단)
<br>
#221 
<br>
- 비회원이 '이 타이틀로 생성하기' 클릭시, 바로 탐색페이지로 리다이렉트 되던 것을 로그인 모달 노출로 변경했습니다!
<br>

Refactor: 리스트 상세 '이 타이틀로 리스트 생성하기' 비회원 접근 시 로직 수정

---

src/app/layout.tsx

- GTM 태그 삽입코드가 적용이 안되는지,,, 구글 태그 매니저에서 태그 감지를 못해 다른 방식으로 삽입해보았습니다.
<br>
- Next에 `import { GoogleTagManager } from '@next/third-parties/google'` 이런게 있길래, 이걸 사용해보았습니다!
-
- 이 방식도 안된다면 새로운 방법도 시도해보겠습니다!

Fix: GTM 태그 재삽입

---

src/app/account/_components/LanguageDropdown.tsx

- 마이페이지 내 각 옵션이 클릭되지 않는 버그를 수정했습니다.
- 언어 변경 드롭다운 컴포넌트(LanguageDropdown)의 로직을 수정했습니다.
<br>
- useOnClickOutSide 훅으로 ref를 가져오는 대신 LanguageDropdown 컴포넌트에서 ref를 생성
- useState로 토글 상태 관리
<br>
- 문제 상황: 지난번 모달 외부 클릭 시 클릭이벤트도 함께 발생하는 버그를 e.preventDefault()로 수정하였습니다.
- 문제 원인: LanguageDropdown 컴포넌트에서 사용하는 ref가 useOnClickOutSide에서 받아올 때 ref.current가 있는 상태이므로, 다른 옵션을 선택했을 때, 클릭 이벤트를 막는 로직을 타서 제대로 동작하지 않았습니다. 
- 해결 방법: 모바일에서 터치시 클릭이벤트가 동작하므로 touchend이벤트를 제거하는 방법과 고민했지만, 근본적인 해결방법이 아닌것 같아서 훅을 사용하지 않고 클릭이벤트(터치이벤트)를 처리하는 방법을 선택했습니다.
<br>
- 브라우저 환경, 모바일 환경에서 모달 테스트를 진행했습니다.
- 서영님 리뷰 부탁드립니다!!🥹 (@seoyoung-min )
- 마이페이지에서 ref를 내려주는 방법을 한번 더 시도해 보겠습니다.🧐
<br>

Hotfix: 마이페이지 드롭다운 컴포넌트 수정(커스텀 훅 대신 useState로 관리)

---

next.config.js
src/app/page.tsx

- 카카오톡이나 인스타그램으로 링크 접속시 열리는 화면은 브라우저 환경이 아님.
- 브라우저 환경이 아니라서, 공유하기 -> 홈화면 추가하기 옵션이 존재하지 않음.
- 아이폰으로 링크 접속 후 바로 뜨는 IOS 앱설치 유도 팝업에서는 홈화면 추가 아이콘을 클릭하라고 안내하기에 혼란을 유발할 가능성이 있음.
- 따라서 **브라우저 환경 접속 후** 공유 및 홈화면 추가 아이콘 클릭을 유도하는 방향으로 프롬프트 메시지 수정함
수정 전
- "1) 공유하기 아이콘"
- "2) 홈화면에 추가"
수정 후
- "1) Chrome 혹은 Safari에서 공유하기 아이콘 누른 후"
- "2) 홈화면에 추가 누르면 완료"
<br>
- IOS PWA prompt 메시지 수정
- localhost에서 pwa 워크박스 관련 개발용 콘솔출력 없앰

Hotfix: IOS PWA앱설치 유도 메시지 수정

---

src/app/start-listy/_components/CreateListStep.tsx

- 온보딩 과정에서 리스트 배경색을 사용하는것을 캐치하지 못해
- 리스트 배경색 확장 작업 이후 발생한 에러 해결
- 추가로 온보딩 과정에서 리스트 배경색을 랜덤으로 설정해주던 방식에서 리스트 배경색을 지정(LISTY_BLUE)해주는 방식으로 변경함.
<br>

ListyWave ver2.4.1 : hotfix - 바뀐 컬러코드로 인해 발생한 온보딩 리스트 생성 랜덤 색상 이슈 처리

---

src/app/auth/redirect/kakao/page.tsx
src/components/login/LoginModal.tsx
src/lib/axios/axiosInstance.ts
src/lib/utils/cookie.ts
src/store/useUser.ts

- 로그인 후 토큰이 저장되는 쿠키의 만료시간을 재설정 했습니다. (24시간에서 14일(2주)로 변경)
<br>
- 리프레쉬 토큰 만료시간을 2주로 재설정 
- 전역 상태 useUser store에 사용자 id만 저장되도록 수정
<br>
- 추후 API 통신 할 때, 토큰을 주고 받는 방식을 Authorization header에서 Set-cookie header로 변경 예정에 따라 현재 리액트 쿠키 사용 관련 로직 변경 예정입니다.
<br>
- 감사합니다!!✨✨
<br>

Refactor: refreshToken 만료시간 재설정

---

src/app/layout.tsx
src/app/list/[listId]/page.tsx
src/app/robots.ts
src/app/sitemap.ts
src/app/user/[userId]/collabolist/page.tsx
src/app/user/[userId]/mylist/page.tsx
src/lib/constants/domain.ts
src/lib/constants/metadata.ts

- 구글 검색엔진 상위 노출을 위한 seo 개선 작업을 진행했습니다.
<br>
- 기존 layout 컴포넌트 metadata 수정 (한글 리스티웨이브 추가)
- 마이리스트, 콜라보리스트, 리스트 상세페이지에 dynamic metadata 설정
- 사용자별, 리스트별로 메타데이터가 설정되도록 반영
- sitemap.ts 설정 (메인, 인트로, 검색페이지, 트렌딩에 해당하는 상세페이지까지 총 13개의 sitemap 추가)
-  사이트맵이란 사이트에 있는 페이지, 콘텐츠의 각 관계에 관한 정보를 제공하는 파일로, 검색엔진은 이 파일을 읽고 사이트를 더 효율적으로 크롤링한다고 합니다.
- robots.ts 파일 추가
<br>
- sitemap 일부 스크린 캡쳐 (sitemap.xml)
<br>
- 해당 pr 머지후에 결과를 살펴보고, 추가로 개선할 부분이 있는지 파악할 예정입니다. 감사합니다. ✨✨
<br>

Refactor: SEO 개선 작업 진행 (metadata, sitemap, robots.txt)
